### ISSUE TITLE
RuntimeError: Not enough space 内存不足？大概要多大内存？16g不够？

### ISSUE THREAD

**Issue by Timfu2019** [lukhy/masr#26]

**Comment by Timfu2019** [comment]
楼主很靓，或者楼主的女票很靓。。   期待楼主回复:)  试了python3.6.8 3.6.5 都显示Not enough space  系统是 manjaro xfce 当前最新版

**Comment by Timfu2019** [comment]
3.6.5 现在显示 RuntimeError: Invalid UTF-8。
[t@t-pc masr]$ python examples/demo-server.py
Loading model...
Traceback (most recent call last):
  File "examples/demo-server.py", line 9, in <module>
    import beamdecode
  File "/home/t/Desktop/asr/masr/examples/../beamdecode.py", line 29, in <module>
    blank_index,
  File "/home/t/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ctcdecode/__init__.py", line 18, in __init__
    self._num_labels)
RuntimeError: Invalid UTF-8
[t@t-pc masr]$ python --version
Python 3.6.5
[t@t-pc masr]$ pyenv local 3.6.8
[t@t-pc masr]$ python --version
Python 3.6.8
[t@t-pc masr]$ python examples/demo-server.py
Loading model...
self._num_labels  4334
Traceback (most recent call last):
  File "examples/demo-server.py", line 9, in <module>
    import beamdecode
  File "/home/t/Desktop/asr/masr/examples/../beamdecode.py", line 29, in <module>
    blank_index,
  File "/home/t/.pyenv/versions/3.6.8/lib/python3.6/site-packages/ctcdecode/__init__.py", line 19, in __init__
    self._num_labels)
RuntimeError: Not enough space
[t@t-pc masr]$

**Comment by Timfu2019** [comment]
换了debian9 没出现问题

**Comment by neoedmund** [comment]
我也是相同的问题， 是内存吗？ 我这是4GB内存。

**Comment by Augustusmyc** [comment]
我也遇到了相同的问题

**Comment by feifaxiaoming** [comment]
8GB的内存，batch_size 只能给到8，在大就死机了
