### ISSUE TITLE
基于anaconda3安装MASR及测试结果

### ISSUE THREAD

**Issue by deepxuexi** [lukhy/masr#37]
基于anaconda3安装：
1.为masr创建一个基于python3.6的虚拟环境，环境名称为masr
conda create -n masr python=3.6 pip numpy jupyter 
2.切换到masr环境
source activate masr
3.安装几个必要的模块
pip install librosa
conda install pytorch-cpu==1.0.1 torchvision-cpu -c pytorch
pip install flask
4.解压ctcdecode.zip到anaconda3/envs/masr/lib/python3.6/site-packages/路径下，这样就不用去辛苦编译ctcdecode啦

MASR及测试结果：

**Comment by yxlwfds** [comment]
(masr) C:\masr>python examples/demo-server.py
Loading model...
Traceback (most recent call last):
  File "examples/demo-server.py", line 9, in <module>
    import beamdecode
  File "C:\masr\examples\..\beamdecode.py", line 6, in <module>
    from ctcdecode import CTCBeamDecoder
  File "C:\Users\hua\Anaconda3\envs\masr\lib\site-packages\ctcdecode\__init__.py", line 1, in <module>
    from ._ext import ctc_decode
ImportError: cannot import name 'ctc_decode'

**Comment by libai3** [comment]
> (masr) C:\masr>python examples/demo-server.py
> Loading model...
> Traceback (most recent call last):
> File "examples/demo-server.py", line 9, in 
> import beamdecode
> File "C:\masr\examples..\beamdecode.py", line 6, in 
> from ctcdecode import CTCBeamDecoder
> File "C:\Users\hua\Anaconda3\envs\masr\lib\site-packages\ctcdecode__init__.py", line 1, in 
> from ._ext import ctc_decode
> ImportError: cannot import name 'ctc_decode'

Please discuss your problem in your issue, not others.

**Comment by libai3** [comment]
Good.

**Comment by XuXin0227** [comment]
hi~,问下 这是完全在windows下操作的吗？

**Comment by linzongzhu** [comment]
你好我想问一下这个环境安装完之后是怎么调用的呢。我是ubuntu，已经按你说的创建了虚拟环境。我下载的作者的源码masr和anaconda3不在同一个文件夹下。我应该怎么调用这个程序实现录音并识别呢？看图之后我没有找到我自己的masr_test.py，是要自己创建？

**Comment by anshshan** [comment]
> 基于anaconda3安装：
> 1.为masr创建一个基于python3.6的虚拟环境，环境名称为masr
> conda create -n masr python=3.6 pip numpy jupyter
> 2.切换到masr环境
> source activate masr
> 3.安装几个必要的模块
> pip install librosa
> conda install pytorch-cpu==1.0.1 torchvision-cpu -c pytorch
> pip install flask
> 4.解压ctcdecode.zip到anaconda3/envs/masr/lib/python3.6/site-packages/路径下，这样就不用去辛苦编译ctcdecode啦
> [ctcdecode.zip](https://github.com/lukhy/masr/files/3321479/ctcdecode.zip)
> 
> MASR及测试结果：
> ![测试结果](https://user-images.githubusercontent.com/35358322/60031293-0b1b8a00-96d7-11e9-987d-c21f0426ae5b.png)

你好，我想问你一下这个test.py文件在原作者里面没有，请问是怎么运行的呢

**Comment by whoconli** [comment]
这个是在Linux环境下做的吗？
因为按照以上步骤在windows配置后，有如下错误：
![image](https://user-images.githubusercontent.com/33571907/62542100-b5b5c980-b88d-11e9-8988-4485c9403a67.png)
然后我在该文件目录找到这个ext文件，里面文件是.so
![image](https://user-images.githubusercontent.com/33571907/62542178-dc740000-b88d-11e9-8e05-9a66be3c1714.png)
网上查了一下，这个好像是linux的运行文件，所以在windows不能使用
是这样吗？

**Comment by jaikydota** [comment]
大家别猜是否是windows了，ctcdecode不能在windows下使用（so库只能在linux下使用，除法有源码能编译dll文件），issus提问者是在linux下anaconda3安装的虚拟环境（可能用的linux虚拟机），作为server。windows下只是作为client使用的。
