### ISSUE TITLE
预训练模型在测试集的CER应该是11%左右？

### ISSUE THREAD

**Issue by bliunlpr** [lukhy/masr#51]
你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。

**Comment by lukhy** [comment]
11%是用你说的方法计算出来的吗？

**Comment by bliunlpr** [comment]
是的，计算出来11%。我用这个代码训练了大概100代，测试大概9%。这个模型还是很赞的！

**Comment by lukhy** [comment]
好的，非常感谢。
既然差别不大，我暂时就不做修改了。

**Comment by v-yunbin** [comment]
@bliunlpr 我训练遇到内存不足的错误，请问你有遇到么

**Comment by bliunlpr** [comment]
我没有遇到过。我的显存是12G，batch-size 为64。如果显存不够，可以减小batch-size。

**Comment by v-yunbin** [comment]
嗯，我试试，多谢啦，我用其他脚本跑1000hr的数据没有内存不足过，只是有点卡。现在这个脚本才有这个问题

**Comment by v-yunbin** [comment]
@bliunlpr 非常感谢，内存不足的问题解决了，再打扰下，训练的时候损失无穷大，不知道为何
```
[1/1000][1065/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1066/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1067/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1068/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
```

**Comment by bliunlpr** [comment]
我也遇到过类似问题，刚开始训练的时候，会有loss为inf。我没管，训练几代之后，这个问题就没有了。

**Comment by v-yunbin** [comment]
@bliunlpr 但是我的是直接训练直接停止了。查了一下原因，好像说这个报错是由于inf引起的。
```
[1/1000][5/32813]       Loss = 273.6400146484375
[1/1000][6/32813]       Loss = 185.6329345703125
[1/1000][7/32813]       Loss = 185.07525634765625
[1/1000][8/32813]       Loss = 148.95761108398438
[1/1000][9/32813]       Loss = 263.52325439453125
[1/1000][10/32813]      Loss = 106.36376190185547
[1/1000][11/32813]      Loss = 206.22174072265625
[1/1000][12/32813]      Loss = 90.67188262939453
[1/1000][13/32813]      Loss = 99.71796417236328
    return self._process_next_batch(batch)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
librosa.util.exceptions.ParameterError: Traceback (most recent call last):
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zyb/masr/data.py", line 58, in __getitem__
    spect = spectrogram(wav)
  File "/home/zyb/masr/data.py", line 31, in spectrogram
    wav, n_fft=n_fft, hop_length=hop_length, win_length=win_length, window=window
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/librosa/util/utils.py", line 170, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

**Comment by bliunlpr** [comment]
这个错误是因为你的语音文件有问题，在计算STFT时出错了。可以检查一下语音文件。

**Comment by v-yunbin** [comment]
@bliunlpr 很棒，检车一下确实有一个非音频路径，多谢

**Comment by v-yunbin** [comment]
@libai3 目前是否支持，训练被暂停后，在从最近一次迭代继续训练？

**Comment by jiahenghuang** [comment]
> 距离
大概训练多长时间可以看到效果。刚开始几个epoch cer都是1

**Comment by jiahenghuang** [comment]
> 你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。

大概训练多长时间可以看到效果。刚开始几个epoch cer都是1

**Comment by bliunlpr** [comment]
前几代还不行，大概十几代之后吧，我训练了100多代，效果还不错。

**Comment by jiahenghuang** [comment]
> 你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。

![image](https://user-images.githubusercontent.com/17797966/60640298-0e421300-9e59-11e9-8298-998057f99bb3.png)
求问这个损失函数正不正常呢？

**Comment by jiahenghuang** [comment]
> 你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。

![image](https://user-images.githubusercontent.com/17797966/60640328-2a45b480-9e59-11e9-8d41-3a1fead1bf7e.png)
这个是每个epoch结束之后，测试集的CER

**Comment by jiahenghuang** [comment]
> > 你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。
> 
> ![image](https://user-images.githubusercontent.com/17797966/60640328-2a45b480-9e59-11e9-8d41-3a1fead1bf7e.png)
> 这个是每个epoch结束之后，测试集的CER

先降低，后来又上升了。然后还会不会下降暂时还不知道

**Comment by v-yunbin** [comment]
@bliunlpr 又遇到了新的错误，有什么建议么
[1/1000][10507/35392]   Loss = inf
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    train(model)
  File "train.py", line 60, in train
    loss = ctcloss(out, y, out_lens, y_lens)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/warpctc_pytorch-0.1-py3.7-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 82, in forward
    self.length_average, self.blank)
  File "/home/zyb/miniconda3/lib/python3.7/site-packages/warpctc_pytorch-0.1-py3.7-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 22, in forward
    grads = torch.zeros(acts.size()).type_as(acts)
RuntimeError: CUDA out of memory. Tried to allocate 938.00 MiB (GPU 0; 7.92 GiB total capacity; 5.81 GiB already allocated; 645.00 MiB free; 1009.94 MiB cached)

**Comment by jiahenghuang** [comment]
> @bliunlpr 非常感谢，内存不足的问题解决了，再打扰下，训练的时候损失无穷大，不知道为何
> 
> ```
> [1/1000][1065/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1066/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1067/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1068/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> ```
> 
> 标记里有英文字符，是这个问题导致？
![image](https://user-images.githubusercontent.com/17797966/60697118-4c077000-9f1b-11e9-9bc8-bdb31c2c3134.png)
loss一直不下降，求问解决方法

**Comment by libai3** [comment]
数据集是什么？

**Comment by jiahenghuang** [comment]
自己的数据

发自我的 iPhone

**Comment by libai3** [comment]
I'm sorry but since I know nothing about your data, there is nothing I can do to give you actual help.
Maybe compare your data with AISHELL since it works fine on AISHELL.

**Comment by jiahenghuang** [comment]
yes,thanks you very much.

发自我的 iPhone

**Comment by Da-Capo** [comment]
可能是label中所有的字符均为未知字符，导致训练label为空。
可以尝试我这里的处理：https://github.com/Da-Capo/Colabstuffs/blob/master/1906_masr.ipynb

**Comment by xiongyihui** [comment]
用 thchs30 数据集和用默认的参数训练，batch size为60时，也出现GPU RAM不足的情况，改小就OK了。另外，也出现 NaN or Inf的问题，把learning rate调小之后，就没出现了（有点怪）。

@jiahenghuang 你的问题可以把learning rate调小试试看。

**Comment by wbjnpu** [comment]
> 你好，我用开源出来的预训练模型，也加上了语言模型，测试集的CER大概11%，并不是8%。我觉得train.py里面的eval(model, dataloader)函数的CER计算是有问题的。函数里面，分别计算了每句话的CER，然后取平均，我认为是有问题的，因为每句话的文本长度是不一致的。应该是统计每句话的编辑距离以及参考文本长度，然后求和，用编辑距离总和 除以 参考文本长度总和，得到最终的CER。

你好，你加的语言模型是百度的那个两个多G的，还是自己训练的语言模型。还有，我训练最低错误率可以达到15%，需要修改哪些详细的参数呢

**Comment by feifaxiaoming** [comment]
@bliunlpr @libai3  麻烦问一下，如果模型中途断了，还能续接训练吗？

**Comment by tanglinjie0815** [comment]
请问内存不足是怎么解决的，需要调整哪些参数，麻烦了

**Comment by tanglinjie0815** [comment]
@v-yunbin 请问您是怎样解决显存不足的，我显存６Ｇ，尝试改小了batch_size但未成功解决

**Comment by jiahenghuang** [comment]
设置为1试试

发自我的iPhone

**Comment by tanglinjie0815** [comment]
@jiahenghuang 尝试过，但还是Segmentation fault (core dumped)

**Comment by feifaxiaoming** [comment]
centos系统和cpu都带不起来，必须得是Linux的ubuntugpu机器才能带起来，不然的话你不加语言模型也没事




| |
黄贺茗
邮箱：hm876556280@163.com
|

签名由 网易邮箱大师 定制

在2020年03月24日 15:12，tanglinjie0815 写道：

@jiahenghuang 尝试过，但还是Segmentation fault (core dumped)

**Comment by tanglinjie0815** [comment]
是的，我用的ubuntu18.04 6G显存

**Comment by jiahenghuang** [comment]
这个bug可不是内存问题哦

发自我的iPhone

**Comment by tanglinjie0815** [comment]
> 这个bug可不是内存问题哦 发自我的iPhone
> […](#)
> 在 2020年3月24日，15:12，tanglinjie0815 ***@***.***> 写道： ﻿ @jiahenghuang 尝试过，但还是Segmentation fault (core dumped) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

恩，那是什么问题导致啊
